### ISSUE TITLE
绑定 Featurize 账号，Featurize 用户名：Ben

### ISSUE THREAD

**Issue by Tuitefen** [featurize/account-binding#41]

**Comment by pengbo0054** [comment]
查无此账号

**Comment by Tuitefen** [comment]
> 查无此账号
![image](https://user-images.githubusercontent.com/81796525/133432543-a086831c-f071-45be-8e75-49f6ddfb3a80.png)

**Comment by Tuitefen** [comment]
> 查无此账号

![image](https://user-images.githubusercontent.com/81796525/133432653-3d5041f3-6689-4ab7-91fa-4968f8e3ecbc.png)

**Comment by Tuitefen** [comment]
是我哪做的不对吗？

**Comment by Tuitefen** [comment]
> 查无此账号

![image](https://user-images.githubusercontent.com/81796525/133433427-fc65823d-4d28-4d69-8ada-1454068c6628.png)

**Comment by pengbo0054** [comment]
应该是 Ben，用户名是大小写敏感的

**Comment by Tuitefen** [comment]
> 应该是Ben，用户名是大小写敏感的

抱歉 那我重新提交一下
